sudo: required
services:
  - docker

before_install:
  - docker build -t johansenlars/frontend -f Dockerfile.dev ./dockerfiles

script:
  - docker run -e CI=true johansenlars/frontend npm run test -- --coverage