sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t image1 -f Dockerfile.dev .

script:
  - docker run -e CI=true image1 npm run test

deploy:
  provider: elasticbeanstalk
  region: "eu-west-1"
  app: "docker-web"
  env: "Dockerweb-env"
  bucket_name:
