name: "Okay"

on:
  push:
    branches: [master, dev]

jobs:
  testitesti:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2

      - name: Install dependencies
        run: npm ci

      - name: Rumpehull
        run: npm test
